### PR TITLE
Adds PSLoggedOn like functionality

### PR DESCRIPTION
**Pull request by breakersall**
Adding in Get-LoggedOnLocal which uses HKU registry checks to see who
is logged locally to a remote box and only requires user level access
rights. The benefit over NetWkstaUserEnum is less user privileges
required (admin for NetWkstaUserEnum) and is the same process
PSLoggedOn uses.

Invoke-PSLoggedOn launches both Get-LoggedOnLocal and Get-NetSessions
and outputs the same format as PSLoggedOn.exe from Sysinternals.

I did not change Invoke-UserHunter non-stealth to this option yet, but
it is beneficial in that if you use both HKU and NetSessionEnum you
only require basic user level rights not admin remote.

### CODE REVIEW

**Comment by mubix** [comment]
This works amazing _if_ RemoteRegistry service is enabled, by default it's in a Manual or even sometime in a Disabled status. Could use some error handling when the remote registry "path" isn't found. Screenshot below is Win10 target in default config (Disabled RemoteRegistry service) then again with the service enabled:

getloggedon

I think with some error handling it would definitely be my first choice when trying to look up who was logged into a box, you might get lucky.

**Comment by mubix** [comment]
Just tried it against a Win2012 box and a Win2k8r2 box, both allowed me to pull info. I don't recall ever changing RemoteRegistry to an enabled status. Would love to see someone confirm this:

loggedonlocal2

**Comment by HarmJ0y** [comment]
Awesome stuff! Confirmed that with remote registry enabled the keys can be read (blows my mind). Confirmed that it works on my 2012 domain controllers (as remote registry is enabled) but fails on stock Win7 boxes (as remote registry is disabled).

There are a few issues that need to be fixed before merging into dev, which I'll enumerate below. If you're able to make the change and resubmit let me know, otherwise I can just land it and make the changes post-merge:
- PowerView uses 4 spaces for indentation instead of tab
- If multiple SIDs are returned (so $UserSID is an array) the code will choke on SID translation as you're trying to treat the collection as a single object. You could pipe **$Reg.GetSubKeyNames() | ? { $_ -match 'S-1-5-21-[0-9]+-[0-9]+-[0-9]+-[0-9]+$' }** straight into ForEach-Object{} to process multiple results.
- Invoke-PSLoggedOn uses Write-Host (which breaks the pipeline). Looking at the code, what might make the most sense is to remove Invoke-PSLoggedOn altogether and I can implement the call to **Get-LoggedOnLocal** somewhere in **Invoke-UserHunter**. Things get tricky when needing to output object of multiple types.

**Comment by HarmJ0y** [comment]
Landing this now and will integrate the change post-merge as we spoke about @breakersall . Thanks again!

**Comment by HarmJ0y** [comment]
The fix is in the dev branch (https://github.com/PowerShellMafia/PowerSploit/commit/b568271d57be6d850906a8c14d5222b81c477daa). I'll start looking into the feasibility of including **Get-LoggedOnLocal** in **Invoke-UserHunter**.

**Pull request merged**
