### PR TITLE
Added ability to specify domain controller to search (-Server parameter)

### PR DESCRIPTION
**Pull request by linuz**
Added the ability for users to specify the domain controller that is searched, using the -Server parameter. The -Server parameter is optional and defaults to the user's current domain if not specified.

### CODE REVIEW

**Comment by breakersall** [comment]
Great minds think alike 👍 

I had a similar submission https://github.com/PowerShellMafia/PowerSploit/pull/145 that i fubar'ed a block up and never fixed; I'll fix that here in a couple days. Similar to yours but honors multiple domains for mass trust searching.

**Comment by HarmJ0y** [comment]
Cool! Could you integrate the following tweaks before we land?

Change 
```
    [CmdletBinding()]
    Param (
            [String]
            $Server
    )
```

to : 
```
    [CmdletBinding()]
    Param (
        [ValidateNotNullOrEmpty()]
        [String]
        $Server = $Env:USERDNSDOMAIN
    )
```

and the if ($Server) {..} else{} block since the default value is now in the parameter.

**Comment by linuz** [comment]
Sure thing! I have made the changes

**Comment by HarmJ0y** [comment]
Also, didn't catch this on first comment, but can you resubmit the pull for the development branch? Our process is to never commit directly to master.

**Comment by linuz** [comment]
Closing this PR; resubmitting to the dev branch

**Pull request closed without merging**
