### PR TITLE
Find AD Managed Security Groups

### PR DESCRIPTION
**Pull request by stufus**
PowerShellEmpire/Empire#119 into PowerSploit. @HarmJ0y asked me to merge it into dev (https://github.com/PowerShellMafia/PowerSploit/pull/104), I agreed and then submitted a PR for master. Trying again :)

### CODE REVIEW

**Comment by mattifestation** [comment]
Thanks for the PR! Note: before this is ultimately merged into master, Find-ManagedSecurityGroups will need to be exported in PowerSploit.psd1 and Recon.psd1.

Cheers,
Matt

**Comment by mattifestation** [comment]
This should also be added to Recon/README.md. Thanks!

**Comment by stufus** [comment]
@mattifestation I've added to README.md, added the exports into the .psd1 files (and I wrote a script to sort all of the psd1 exports into alphabetical order so that the subdirectory ones are in keeping with Powersploit.psd1, hope that helps)

**Comment by mattifestation** [comment]
Great stuff. Thanks!

**Comment by HarmJ0y** [comment]
Thanks @stufus !

**Pull request merged**
